apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-service
data:
  application.yml: |-
    server:
      port: 8080
      error:        
        include-message: always
        include-binding-errors: always
        forward-headers-strategy: framework
    spring:
      h2:
        console:
          enable: true
      datasource:
        url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        platform: h2
        username: sa
        password:
        initialization-mode: always
      jpa:
        defer-datasource-initialization: true
        show-sql: true
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
          hibernate:
            format_sql: false
            show_sql: true
            use_sql_comments: false
      cloud:
        kubernetes:
          discovery:
            all-namespaces: true
    logging:
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-5%p} %m%n"
      level:
        org:
          hibernate:
            SQL: DEBUG
            type: TRACE
    management:
      endpoints:
        web:
          base-path: /invoices/actuator
          exposure:
            include: "*"
      metrics:
        enable:
          all: true
    springdoc:
      api-docs:
        path: /invoices/openapi
      swagger-ui:
        path: /invoices/swagger
    feign:
      client:
        url:
          customer: http://customer-service-service:8080
          product: http://product-service-service:8080